/**
 * YouTube-specific type definitions
 */

export interface YouTubeVideoMetadata {
  videoId: string;
  title: string;
  description: string;
  channelId: string;
  channelTitle: string;
  publishedAt: string;
  duration: string;
  viewCount: number;
  likeCount?: number;
  commentCount?: number;
  tags?: string[];
  categoryId: string;
  defaultLanguage?: string;
  thumbnails: {
    default?: YouTubeThumbnail;
    medium?: YouTubeThumbnail;
    high?: YouTubeThumbnail;
    standard?: YouTubeThumbnail;
    maxres?: YouTubeThumbnail;
  };
}

export interface YouTubeThumbnail {
  url: string;
  width: number;
  height: number;
}

export interface YouTubeTranscript {
  text: string;
  language: string;
  isAutoGenerated: boolean;
  segments?: YouTubeTranscriptSegment[];
}

export interface YouTubeTranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface YouTubePlaylistItem {
  videoId: string;
  title: string;
  description: string;
  publishedAt: string;
  channelTitle: string;
  position: number;
}

export interface YouTubeExtractionResult {
  metadata: YouTubeVideoMetadata;
  transcript?: YouTubeTranscript;
  error?: string;
}

export interface YouTubeApiError {
  code: number;
  message: string;
  errors: Array<{
    domain: string;
    reason: string;
    message: string;
  }>;
}

// Composio-specific types
export interface ComposioYouTubeParams {
  videoId: string;
  part?: string[];
  languageCode?: string;
}

export interface ComposioYouTubeResponse {
  success: boolean;
  data?: any;
  error?: YouTubeApiError;
} 